name: Debug Pipeline

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Show files
        run: |
          pwd
          ls -la
          ls -la backend
          ls -la frontend

      - name: Backend
        working-directory: backend
        run: |
          node -v
          npm -v
          npm ci
          npm run lint

      - name: Frontend
        working-directory: frontend
        run: |
          node -v
          npm -v
          npm ci
          npm run lint
