name: hadolint-scan

on:
    workflow_call:

jobs:
    hadolint:
        strategy:
            matrix:
                folder: ["frontend","backend"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ${{ matrix.folder }}/Dockerfile