name: MemeApp-CICD
on: workflow_dispatch

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install deps
        run: |
          npm ci
          cd ../frontend && npm ci
        working-directory: backend

      - name: Run lint
        run: |
          npm run lint
          cd ../frontend && npm run lint
        working-directory: backend

      - name: Run tests
        run: |
          npm test
          cd ../frontend && npm test
        working-directory: backend

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-test-lint
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/memegen-frontend:latest
            ${{ vars.DOCKERHUB_USERNAME }}/memegen-frontend:${{ github.sha }}

      - uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/memegen-backend:latest
            ${{ vars.DOCKERHUB_USERNAME }}/memegen-backend:${{ github.sha }}
