name: Meme-Generator-CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
    
    secret-scanning:
        uses: ./.github/workflows/secret-scan.yml
    
    dep-scanning:
        needs: [lint]
        uses: ./.github/workflows/dep-check.yml

    code-scan:
        uses: ./.github/workflows/code-scan.yml

    hadolint-scan:
        needs: [lint, secret-scanning, dep-scanning, code-scan]
        uses: ./.github/workflows/docker-hadolint.yml

